Check if user is admin before warning
tripal/tripal pull request #1284
Opened 2022-06-28 16:23 UTC by Ferrisx4

# Bug Fix

Issue #1283

## Description

The user would be warned if Drupal could not find details about a vocabulary, even if they are not an admin.

## Testing?
Testing is difficult due to the root of this issue mostly being solved by https://github.com/tripal/tripal/issues/500, although some sites still may encounter this infrequently. This message typically appears after a cache clear. If your site suffers from the warning, it should not be shown unless you are logged in as an admin.

## Additional Notes:

While this issue and PR address a specific case of warnings/messages for admins being shown to any user, it is not the only such case. As current Tripal 3 development is mostly over, it is and should be a consideration in Tripal 4 and beyond to ensure that messages only get shown to appropriate users.

2022-08-19 17:11 UTC, dsenalik requested changes
Line 109 should be
``` if ($user->uid && ...```
otherwise I don't think the message will ever appear, an administrator will always have a uid.

2022-08-21 23:47 UTC, spficklin approved these changes

2022-08-21 23:56 UTC, spficklin requested changes
We have an API function for targetting Tripal admin users.  Try this function: `tripal_set_message` instead of checking for the administrator user.

http://api.tripal.info/api/tripal/tripal_core%21api%21tripal_core.tripal.api.inc/function/tripal_set_message/2.x

2022-08-30 23:09 UTC, spficklin approved these changes

2022-08-30 23:10 UTC, merged

2022-08-30 23:11 UTC, spficklin commented
Thanks @Ferrisx4 !  The switch to use tripal_set_message means that the fix requested by @dsenalik wasn't also addressed.

2022-08-31 12:53 UTC, Ferrisx4 commented
Yes, thanks!