Tv4g1 issue1414 data  sequence length updated code
tripal/tripal pull request #1607
Opened 2023-08-15 23:24 UTC by pdtouch

Code is cleaned up, removing unnecessary classes and code, added feature to not show checksum if sequence is not provided. Tested functionality

#

Issue #

### Tripal Version: 

## Description

## Testing?

2023-08-15 23:56 UTC, laceysanderson commented
## Notes

- This PR is dependant upon #1604. It cannot be merged until that one is first.
- This PR includes the work of @srobb1 done in PR #1419. As such we are closing #1419 in favour of this one.
- Testing instructions for this PR are in #1419 
- We will want to ensure the new fields are automatically attached via the YAML.

Thanks @pdtouch <3

2023-08-17 17:58 UTC, dsenalik commented on tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceChecksumDefault.php
> + * )
Add `*   cardinality = 1` here

2023-08-17 18:04 UTC, dsenalik requested changes
I followed the testing steps, and the field worked perfectly.
- [x] Entering a simple sequence
![1](https://github.com/tripal/tripal/assets/8419404/cd2a08fd-83b2-4a57-b0b3-e87e756c51f9)

displays 
![2](https://github.com/tripal/tripal/assets/8419404/03eeba14-f4e3-4d53-83fa-e3d35f230768)
and I verified the correctness of this checksum
`echo -n cat | md5sum`
`d077f244def8a70e5ea758bd8352fcd8  -`

- [x] Changing the sequence updates the length and checksum correctly.

- [x] A long sequence is correctly wrapped to the same length as for Tripal 3.

- [x] If I add extra white space, it is removed when I save. I just checked, and this is what Tripal 3 does, so I guess this is correct.

- [x] I configured a default value, and it showed up correctly when creating a new gene

- [x] In my container I am seeing the field debugger output, but I never turned that on. I'm not sure yet if that's a problem with this PR or not. Checking it here, and reference on PR#1604 in this comment https://github.com/tripal/tripal/pull/1604#issuecomment-1682760409
![3](https://github.com/tripal/tripal/assets/8419404/c98e88f7-3fd0-4c58-a7fc-6aaeeb3761c0)

Changes requested:
- [x] The cardinality for this field should be set permanently to 1. This field will only apply to the feature table, and you can only have one sequence. You can add
`*   cardinality = 1` I have a separate comment showing where

- [x] In ChadoSequenceWidgetDefault.php you use a variable `$rec_id_val` but it is never set in this function, something might be wrong here

- [x]  Figure out why testing is failing

2023-08-17 20:59 UTC, laceysanderson commented
The testing is failing on this branch due to the inclusion of the code from PR #1604. It has been fixed in that PR so please update this branch as well.

2023-08-21 15:22 UTC, laceysanderson commented
Tests are now passing!
Should just be the two remaining comments in @dsenalik review:

> The cardinality for this field should be set permanently to 1. This field will only apply to the feature table, and you can only have one sequence. You can add `cardinality = 1` I have a separate comment showing where.

> In ChadoSequenceWidgetDefault.php you use a variable $rec_id_val but it is never set in this function, something might be wrong here

2023-08-21 17:22 UTC, dsenalik approved these changes
Approved with suggested changes added.

2023-08-21 17:50 UTC, merged