Newick Importer
tripal/tripal pull request #1618
Opened 2023-08-28 04:41 UTC by risharde

Attempt #1 - Latest newick importer for Tripal 4
- Special thanks to Doug @dsenalik for finding test tree
- Conversion from Tripal 3 (Drupal 7) code to Tripal 4 (Drupal >=9) form and related deprecated functions
- Upgrades for chado_* functions to use Database API instead
- Minor adjustment was made to Tree Type select search querying
- Removal of option to create branch job to process trees (old feature in Tripal 3), permission granted by @spficklin 
- 16 unit tests which currently pass.
- Latest pull from 4.x (minor merge conflicts resolved)

2023-08-28 15:08 UTC, dsenalik requested changes
I built a docker with drupal 9.5, php 8.0 and I am seeing this trying to access the loader form
```
The website encountered an unexpected error. Please try again later.

Symfony\Component\Routing\Exception\MissingMandatoryParametersException: Some mandatory parameters are missing ("cv_id") to generate a URL for route "tripal_chado.cvterm_autocomplete". in Drupal\Core\Routing\UrlGenerator->doGenerate() (line 181 of core/lib/Drupal/Core/Routing/UrlGenerator.php).

Drupal\Core\Routing\UrlGenerator->getInternalPathFromRoute('tripal_chado.cvterm_autocomplete', Object, Array, Array) (Line: 291)
Drupal\Core\Routing\UrlGenerator->generateFromRoute('tripal_chado.cvterm_autocomplete', Array, Array, 1) (Line: 105)
Drupal\Core\Render\MetadataBubblingUrlGenerator->generateFromRoute('tripal_chado.cvterm_autocomplete', Array, Array, 1) (Line: 765)
Drupal\Core\Url->toString(1) (Line: 191)
...
```
I will try my other docker building on drupal 10 and report any updates...

Failing the same way on drupal 10.1 php 8.1

2023-08-28 15:08 UTC, dsenalik commented on tripal_chado/src/Plugin/TripalImporter/NewickImporter.php
> +    // $form['load_later'] = [
Yay for removing this entirely! I think you should remove this commented out code.

2023-08-28 15:08 UTC, dsenalik commented on tripal_chado/src/Plugin/TripalImporter/NewickImporter.php
> +    $leaf_type = explode(' ', $leaf_type)[0]; // splits the string by space and takes the first part
This can be fixed using the same technique as is now in the fasta loader. So here pass through the full string unmodified, and where we look up the cvterm_id we can use
```
use Drupal\tripal_chado\Controller\ChadoCVTermAutocompleteController;
...
    $cv_autocomplete = new ChadoCVTermAutocompleteController();
    $cvterm_id = $cv_autocomplete->getCVtermId($type, 'sequence');
```

2023-08-28 15:32 UTC, dsenalik commented
I went ahead and pushed the simple fix for the autocomplete route problem so that we can proceed with testing this. The autocomplete went through some changes while you were working on this, so I bet you last 4.x merge is what broke it.

2023-08-28 16:25 UTC, dsenalik commented
Okay I have successfully loaded two trees different from the "test" ones. Issues to fix
- [ ] If you forget to specify a tree file, this is not validated, and it attempts to load with no tree, and generates many errors
- [ ] I request we add the extension `.newick` to the list of valid file extensions
- [ ] I tried to specify 'taxonomy' as the tree type, and saw some deprecations
` [warning] WARNING: DEPRECATED: the 'tripal_report_error' function will be removed from the API in a future release.`
` [warning] WARNING: DEPRECATED: the 'tripal_log' function will be removed from the API in a future release.`
- [ ] I tried to test creating a dbxref, I used `MAIN:bogus` as the dbxref, but `MAIN` is not an existing db, we need to validate for this
```
'dbxref' returned no results where the definition supplied was Array(    [name] => MAIN)
ERROR: 
              dbxref could not be created for db: <em class="placeholder"></em>.
 [error]  ERROR: 
              dbxref could not be created for db: <em class="placeholder"></em>. 
[site http://default] [TRIPAL] ERROR:               dbxref could not be created for db: <em class="placeholder"></em>.
```
If I use an existing db i.e. `local:bogus` I get a wsod
`The website encountered an unexpected error. Please try again later.`

`Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bigint: "Array" LINE 1: ...."dbxref" ("accession", "db_id") VALUES ('bogus', 'Array') R... ^: INSERT INTO "chado"."dbxref" ("accession", "db_id") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1) RETURNING dbxref_id; Array ( ) in chado_validate_phylotree() (line 254 of modules/contrib/tripal/tripal_chado/src/api/tripal_chado.phylotree.api.php). `

2023-08-28 16:58 UTC, risharde commented
Thanks for the review @dsenalik - will try to work on fixes!

2023-08-28 19:35 UTC, risharde commented
@dsenalik Issue number 3 ( I tried to specify 'taxonomy' as the tree type, and saw some deprecations).

I can't seem to reproduce these warnings - could you attach the tree file you might be testing? I also looked for any function calls mentioned in those deprecation warnings and could find any calls in the tripal_chado.phylotree_newick.api.php file nor the tripal_chado.phylotree.api.php files so I'm having issues trying to find where this might be happening.

2023-08-28 20:31 UTC, risharde commented on tripal_chado/src/Plugin/TripalImporter/NewickImporter.php
> +    // $form['load_later'] = [
Will do in next push, coming up in a few minutes.

2023-08-28 20:58 UTC, dsenalik commented
Well that's what happens when you juggle three dockers at the same time. I can't reproduce it either with any of the trees I tested with. I have checked this off the list, and if you can't find it in the code I think we should ignore this one. 🙈

2023-08-28 21:04 UTC, risharde commented
No prob @dsenalik, thanks for letting me know!

2023-08-31 12:34 UTC, dsenalik commented
Testing loading a tree with `.newick` extension, type=`taxonomy` I have this to investigate

Drupal\Core\Database\RowCountException: rowCount() is supported for DELETE, INSERT, or UPDATE statements performed with structured query builders only, since they would not be portable across database engines otherwise. If the query builders are not sufficient, use a prepareStatement() with an $allow_row_count argument set to TRUE, execute() the Statement and get the number of matched rows via rowCount(). in Drupal\Core\Database\StatementWrapperIterator->rowCount() (line 243 of core/lib/Drupal/Core/Database/StatementWrapperIterator.php).

Drupal\tripal_chado\Plugin\TripalImporter\NewickImporter->formValidate(Array, Object) (Line: 269)
Drupal\tripal\Form\TripalImporterForm->validateForm(Array, Object)
call_user_func_array(Array, Array) (Line: 82)
Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object) (Line: 275)
Drupal\Core\Form\FormValidator->doValidateForm(Array, Object, 'tripal_admin_form_tripalimporter') (Line: 118)
Drupal\Core\Form\FormValidator->validateForm('tripal_admin_form_tripalimporter', Array, Object) (Line: 593)
Drupal\Core\Form\FormBuilder->processForm('tripal_admin_form_tripalimporter', Array, Object) (Line: 325)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
...

2023-08-31 13:15 UTC, dsenalik commented
I pushed commit  to fix this so I can continue testing. I made the dbxref validation more robust by making sure there is a colon with something on both sides of the colon. Test with: empty (pass) `:T12345` (fail) `local:` (fail) `:` (fail) `bogusdb:T12345` (fail) `local:T12345` (pass)

2023-08-31 16:22 UTC, dsenalik commented
I pushed commit https://github.com/tripal/tripal/pull/1618/commits/6b2be1466a9dbfe73e16bd6e5760026b0453c4d3 to fix these last two errors, one is a PHP8.2 warning, and I updated some more validation.

`chado_validate_phylotree()` is now called after the file validation, no point calling it if no file was specified.

All instances of `setError()` except the final summary one are converted to `setErrorByName()` so that the appropriate form element is highlighted.

Importing is working without errors for a taxonomy tree. I created a couple of test organisms, then tested loading with a `Feature Name Regular Expression` of `S_\d+(.*)` to allow matching, e.g. `Import phylotree: Associated S18540_Asteriscium_chilense to organism_id: 2`

2023-08-31 17:42 UTC, dsenalik approved these changes

2023-08-31 17:45 UTC, dsenalik commented
@risharde I pushed one last commit https://github.com/tripal/tripal/pull/1618/commits/b81c2aeb6c24ebe05954a113ce239248efc7bbf8 to remove the Tripal 3 code that was commented out and update the tripal.logger parameters, and as far as I am concerned this is good to go, working on the fussy PHP 8.2 without any complaints.

And I removed all traces of the "load later" code 💣

2023-09-15 00:18 UTC, spficklin approved these changes

2023-09-15 00:19 UTC, spficklin commented
This looks good.  It loaded the tree just fine, but we do need a way to visualize it.  But visualization is a field. So, I'm going to merge this into core and add an issue related to tree visualization so that we remember when whoever does the field for tree viewing that they remember to check the tree. If it doesn't get added in correctly then we'll have to debug the loader further.

2023-09-15 00:20 UTC, merged