Tv4g1 1509 sequence fields
tripal/tripal pull request #1619
Opened 2023-08-28 16:56 UTC by pdtouch

Modified the tripal_chado tripal_collections YAML file to include new fields into the gene page bundle.

#

Issue #1509

### Tripal Version: 

## Description

## Testing?

2023-08-28 17:00 UTC, dsenalik requested changes, later dismissed
Code changes requested. I will build a docker for functional testing...

2023-08-28 17:00 UTC, dsenalik commented on tripal_chado/src/Plugin/Field/FieldFormatter/ChadoLocalSourceDataFormatterDefault.php
> +>>>>>>> b73440286faed0b3cf68dec7fdff3e2bb4528450
You need to remove the three merge conflict lines <<<< ===== and >>>>>

2023-08-28 17:00 UTC, dsenalik commented on tripal_chado/src/Plugin/Field/FieldType/ChadoLocalSourceDataDefault.php
> +>>>>>>> b73440286faed0b3cf68dec7fdff3e2bb4528450
Remove <<<<< ===== >>>>> lines

2023-08-28 17:00 UTC, dsenalik commented on tripal_chado/src/Plugin/Field/FieldWidget/ChadoLocalSourceDataWidgetDefault.php
> +>>>>>>> b73440286faed0b3cf68dec7fdff3e2bb4528450
same here

2023-08-28 17:29 UTC, dsenalik commented
I added a testing procedure to this PR, but unfortunately the length and checksums are not working
![gene-not-working](https://github.com/tripal/tripal/assets/8419404/0ef83a01-70e1-4f40-89c0-4d77d6036a3d)

2023-08-29 21:29 UTC, dsenalik commented
Debugging this, it seems that the checksum is generated, but is not found in the chado.feature table.
I suspect that maybe the checksum field is interfering and saving its null, somehow overriding saving the md5checksum from the sequence residues field. Maybe the order is important and that is why it is working when these three fields are added manually.
![not-saving](https://github.com/tripal/tripal/assets/8419404/ab88edac-9bd5-4c48-9a30-e0b512c293c3)

2023-08-30 16:38 UTC, laceysanderson commented
Interesting! I was actually noticing in making documentation that we didn't have a way to indicate that a field should read a column in the base table but not write. Currently we only have store as the join clearly doesn't work and is not meant for base table columns.

If making the widget non-functional (i.e. remove the form elements) doesn't work then this may need a small update to chado storage for this case.

2023-08-30 16:56 UTC, dsenalik commented
If the widgets are disabled, then the main field properly updates the sequence, length, and checksum and it is stored in the feature table.
However, the length and checksum fields do not appear. I am sure now that this is the problem of fields not picking up records not added through the field, as you @laceysanderson mentioned in this comment. https://github.com/tripal/tripal/issues/1546#issuecomment-1642429013
Until we get that fixed, I think this PR will have to stay on hold.
I think the field "accidentally" worked before because by chance the order was right, and the other widgets caused the appropriate records to get generated in the `tripal_entity__gene_sequence_md5_checksum` and `tripal_entity__gene_length` tables, but the main field by chance saved last and generated the correct data.

2023-10-05 18:46 UTC, laceysanderson commented
To use the new functionality in PR #1663, you will need to make the following changes:

```diff
diff --git a/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceChecksumDefault.php b/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceChecksumDefault.php
index de2b082fb..7b4896beb 100644
--- a/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceChecksumDefault.php
+++ b/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceChecksumDefault.php
@@ -79,12 +79,12 @@ class ChadoSequenceChecksumDefault extends ChadoFieldItemBase {
         'chado_column' => 'feature_id'
     ]);
     $properties[] =  new ChadoIntStoragePropertyType($entity_type_id, self::$id, 'seqlen', $seqlen_term, [
-      'action' => 'store',
+      'action' => 'read_value',
       'chado_column' => 'seqlen',
       'chado_table' => 'feature'
     ]);
     $properties[] =  new ChadoBpCharStoragePropertyType($entity_type_id, self::$id, 'md5checksum', $md5checksum_term, $md5_checksum_len, [
-      'action' => 'store',
+      'action' => 'read_value',
       'chado_column' => 'md5checksum',
       'chado_table' => 'feature'
     ]);
diff --git a/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceLengthDefault.php b/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceLengthDefault.php
index 3463716b5..cadfcad80 100644
--- a/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceLengthDefault.php
+++ b/tripal_chado/src/Plugin/Field/FieldType/ChadoSequenceLengthDefault.php
@@ -16,7 +16,7 @@ use Drupal\tripal_chado\TripalStorage\ChadoIntStoragePropertyType;
  *   default_formatter = "chado_sequence_length_formatter_default"
  * )
  */
- 
+
 
 class ChadoSequenceLengthDefault extends ChadoFieldItemBase {
 
@@ -73,7 +73,7 @@ class ChadoSequenceLengthDefault extends ChadoFieldItemBase {
         'chado_column' => 'feature_id'
     ]);
     $properties[] =  new ChadoIntStoragePropertyType($entity_type_id, self::$id, 'seqlen', $seqlen_term, [
-      'action' => 'store',
+      'action' => 'read_value',
       'chado_column' => 'seqlen',
       'chado_table' => 'feature'
     ]);
```

This PR also needs these fields to be added to the other feature-based content types. Specifically, mRNA, genetic marker, sequence variant, heritable phenotypic marker, QTL using the YAML in the same way you did for gene.

2023-10-18 01:43 UTC, pdtouch commented
Requested changes are incorporated and testing completed successfully.
The Sequence Length and Checksum fields were added to other tripal content types :
`mRNA, genetic marker, sequence variant, heritable phenotypic marker, QTL` in addition to `Gene` 

![Screenshot 2023-10-17 at 7 19 20 PM](https://github.com/tripal/tripal/assets/2090189/be3fac55-36c2-4ead-b0be-63394b521b50)

![Screenshot 2023-10-17 at 7 15 25 PM](https://github.com/tripal/tripal/assets/2090189/85f308a0-52e0-4e66-83c8-659bcfe56e08)

![Screenshot 2023-10-17 at 7 15 38 PM](https://github.com/tripal/tripal/assets/2090189/77e346ae-98fa-4cce-bbcc-ec8894f19a74)

2023-11-01 18:56 UTC, laceysanderson approved these changes
✅ Code looks good
✅ Requested changes were addressed
✅ All 3 fields showed up by default on all feature-based content types (i.e. gene, mRNA, genetic marker, sequence variant, QTL, heritable phenotypic marker)
✅ Fields correctly saved sequence residues, calculated length and mD5sum (see screenshot)
✅ No errors when creating content without the sequence set. sequence length set to 0 and md5sum hidden.
✅ No errors when content edited and sequence removed. sequence length updated to 0 and md5sum hidden.

I think this is ready to merge!

2023-11-01 19:19 UTC, dsenalik approved these changes
I did a quick test too and it worked for me

2023-11-01 19:20 UTC, merged