Modified 3 tripaldocker/Dockerfiles for PHP 8.1, 8.2 and 8.3 to accom…
tripal/tripal pull request #1784
Opened 2024-02-15 20:55 UTC by pdtouch

Accommodate upload of files-size upto 8MB

 Accommodate upload of files-size upto 8MB
#

### Issue #
1749 

### Tripal Version: 
4
## Description

Docker files were modified to accommodate upload of files like larger FASTA genome and scaffold files of size upto 8MB. Earlier limit was 2MB.

Example genomics site has a FASTA file of size 6 MB. Attempt to upload this file via the Chado FASTA File Loader page throws error:
 
`Unfortunately, you can not upload this file as the size exceeds the the maximum file size allowed by this site: 2.1MB. You can manage the maximum file upload size by changing the upload_max_filesize in your php.ini file.
`
## Testing?

Use the new dockerfiles, for example to use php8.2-pgsql13 with Drupal 10.1x-dev,

```
cntr_name="Tripal_4_Drupal_10.1.x_PHP8.2_PG13"

sudo docker build --tag=tripaldocker:$cntr_name \
 --build-arg drupalversion=10.1.x-dev \
 --file tripaldocker/Dockerfile-php8.2-pgsql13 ./

sudo docker run --publish=5207:80 -tid \
    --name=$cntr_name \
    --volume=$(pwd):/var/www/drupal/web/modules/contrib/tripal \
    tripaldocker:$cntr_name 

sudo docker exec $cntr_name service postgresql restart

sudo docker exec -it $cntr_br_name /bin/bash

grep -i upload_max_filesize /usr/local/etc/php/php.ini

```
would result in:

`upload_max_filesize = 8M
`
With the previous versions of the docker files, it was:

`upload_max_filesize = 8M
`

Checking the feature on the web url:
`http://localhost:5207
`

**Tripal -> Data Loaders -> Chado FASTA File Loader -> Browse FASTA file**
and upload the file 'Citrus_sinensis-scaffold00001.fasta' of size 6MB.

http://tripal.info/sites/default/files/Citrus_sinensis-scaffold00001.fasta

Ref: https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/genomes_genes.html

2024-02-15 22:02 UTC, dsenalik requested changes
* Every separate `RUN` command in the docker file adds a little bit of extra time to the build process, so it is best to combine simple related tasks, see my suggested changes. I also moved the `/` in the sed commands to what seems a better place.
 * I tested building a `7M` docker to test the ability to set at build time, this worked.
 * I tested the fasta upload and it worked.

2024-02-15 22:02 UTC, dsenalik commented on tripaldocker/Dockerfile-php8.1-pgsql13
> +
```suggestion
RUN echo 'memory_limit = 1028M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini \
  && sed -i 's/upload_max_filesize = 2M/upload_max_filesize = '"$phpuploadsize"'/' /usr/local/etc/php/php.ini

```

2024-02-15 22:02 UTC, dsenalik commented on tripaldocker/Dockerfile-php8.2-pgsql13
> +
```suggestion
RUN echo 'memory_limit = 1028M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini \
  && sed -i 's/upload_max_filesize = 2M/upload_max_filesize = '"$phpuploadsize"'/' /usr/local/etc/php/php.ini

```

2024-02-15 22:02 UTC, dsenalik commented on tripaldocker/Dockerfile-php8.3-pgsql13
> +
```suggestion
RUN echo 'memory_limit = 1028M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini \
  && sed -i 's/upload_max_filesize = 2M/upload_max_filesize = '"$phpuploadsize"'/' /usr/local/etc/php/php.ini

```

2024-02-15 22:32 UTC, pdtouch commented
Dockerfiles were changed as requested. Thanks!

2024-02-16 03:03 UTC, dsenalik approved these changes

2024-02-16 03:04 UTC, merged