URL and name field filters default to plain text
tripal/tripal pull request #1871
Opened 2024-05-05 18:47 UTC by dsenalik

# Bug Fix

### Closes #1864

### Tripal Version: 4.x

## Description
This changes the default filter for `text` (i.e. unlimited length) fields from `basic_html` (the default) to `plain_text` for those fields that should not have formatting. Specifically, any URI field should not allow formatting, and fields likely to be used in a content type title, such as a `name` field, should also be plain_text.

## Testing?
 * Build a new docker on this branch.
 * Create a protocol.
The uri field should not show a formatting toolbar, and once saved, the title should no longer have HTML paragraph tags.
 * Test array design, assay, biomaterial, and study to make sure titles do not show paragraph tags
 * Test analysis, qgenome assembly, and genome annotation to make sure URI fields do not have a formatting toolbar.

2024-05-09 17:56 UTC, laceysanderson requested changes
- ✅ Protocol
- ✅ Array Design
- ❌ Assay
- ✅ Biological Sample
- ✅ Study

I also noticed in Assay there are two Array Batch Identifiers and the second one takes priority. There is an error shown related to the TripalEntityLookup service. See screenshots:

| View | Edit |
|------|------|
| ![assayContentType](https://github.com/tripal/tripal/assets/1566301/57347dda-0b28-40b1-9fbd-9d38486243fd) | ![assayContentTypeEdit](https://github.com/tripal/tripal/assets/1566301/aa3d6e0a-469f-4850-980d-f6b5181cda76) |

2024-05-15 17:57 UTC, dsenalik commented
I have hopefully resolved the two noted problems
 1. I remove the first of the two duplicated fields with commit https://github.com/tripal/tripal/pull/1871/commits/f149c96433349f7126123703223997ba4782ce04 - the second one is more logically placed and better matches Tripal 3 I think.
 2. The error happens if the array specifying required fields is cached by `getRequiredFields()`, then a new Type Collection is imported. I adjusted the code to re-cache if the `bundle_id` is missing, which will cover this case. Commit https://github.com/tripal/tripal/pull/1871/commits/a63c800006a2ac581611ee5370f0ad81b4fed4cc

2024-05-15 18:30 UTC, dsenalik commented
3. I changed Assay title to plain text to resolve the last remaining title with &lt;p&gt;&lt;/p&gt; tags, commit https://github.com/tripal/tripal/pull/1871/commits/9cf6bfc86e174daebac7804dc47cdb0ee0e56817

2024-05-21 17:58 UTC, laceysanderson approved these changes
✅ The code updates look good
✅ I don't get the error anymore
✅ Assay name is no longer rich text

Thus I am marking it as approved :-) 

That said, I did notice we have one more duplicated field 🙈 Specifically Array Identifier (assay_arrayidentifier) and Unique Name (assay_unique_name) both indicate assay.arrayidentifier as their chado column. I only caught it because I filled in uniquename but not array identifier and it kept not saving my indicated uniquename.

2024-05-21 19:41 UTC, dsenalik commented
I wrote a program to scan all the yaml just to make sure there are no others - that seems to be the only case - thanks for finding it!

2024-05-21 21:34 UTC, laceysanderson commented
Great! This is ready to merge once the tests pass again from the recent merge!

2024-05-21 21:54 UTC, merged