Drush command to update chado instance to match Tripal Term expectations
tripal/tripal pull request #1895
Opened 2024-06-11 19:47 UTC by laceysanderson

# Tripal 4 Core Dev Task

### Issue #1698 

### Tripal Version: 4

## Description

This PR adds a drush command that will check a specific chado instance to ensure it matches the expectations set out by Tripal 4. This is needed because chado vocabularies and cvterms often become a bit eccentric over the years ;-p Right now, we are finding that running the prepare step in Tripal 4 on a chado exported from a Tripal 3 site fails due to changes in term expectations, definitions, etc.

More specifically, the drush command `drush trp-check-terms --chado_schema=chado` would run a number of checks on the cv, db, cvterm, and dbxref tables to ensure the values associated with key Tripal terms match those defined in the [Chado Content Terms YAML](https://github.com/tripal/tripal/blob/4.x/tripal_chado/config/install/tripal.tripal_content_terms.chado_content_terms.yml). This command also offers the option in some cases to fix any deviations from what is expected.

- [x] Create the command stub/documentations/test
- [x] VOCAB: check for missing cvs and for different cv.definitions
- [x] ID SPACE: check for missing dbs and for different description, url, and urlprefix.
- [ ] TERM: Check for difference in definition.
- [ ] TERM: cvterm.name, dbxref.accession, dbxref.db match + are connected.
- [ ] TERM: cvterm.name, cvterm.cv, and dbxref.accession match + are connected.
- [ ] TERM: all match but are not connected.
- [ ] TERM: it's just missing which is not actually a problem.
- [x] Fixes for small deviations in vocab and id space.
- [ ] Evaluate additional fixes.

## Testing?

I started automated testing for this!

Alternatively, you can test by running the drush command and inspecting it's output. 
- On a freshly installed site the command should show there are no errors or warnings.
- Change a cv.definition, db.description, db.url or db.urlprefix and confirm they show up highlighted yellow in the summary table and the specific change is described more fully under warnings. Also confirm that if you ask to fix it that the command does correctly.

2024-06-18 00:36 UTC, dsenalik commented
I feel like the defaults should be "non-destructive"
What do you thing about changing
`Would you like us to update the descriptions of your chado cvs to match our expectations? (yes/no) [yes]`
to
`Would you like us to update the descriptions of your chado cvs to match our expectations? (yes/no) [no]`
and similar changes later?

2024-06-18 12:50 UTC, dsenalik commented on tripal_chado/src/Commands/ChadoCheckTermsAgainstYaml.php
> +    // Also, indendantly select the dbxref...
```suggestion
    // Also, independently select the dbxref...
```

2024-06-18 12:58 UTC, dsenalik commented
This is a note to remind me for a different issue, I was wondering why `local:lineage` was showing up twice, it is because it is duplicated in `tripal_chado/config/install/tripal.tripal_content_terms.chado_content_terms.yml`
I stuck in some code to check for others, the only other duplication is
`array design (EFO:0000269)`
Issue #1900

2024-06-18 15:40 UTC, dsenalik commented on tripal_chado/src/Commands/ChadoCheckTermsAgainstYaml.php
> +    $this->io()->section('Term (cvterm/dbxref Issues.');
```suggestion
    $this->io()->section('Term (cvterm/dbxref) Issues.');
```

2024-06-18 16:21 UTC, laceysanderson commented
> I feel like the defaults should be "non-destructive" What do you think about changing `Would you like us to update the descriptions of your chado cvs to match our expectations? (yes/no) [yes]` to `Would you like us to update the descriptions of your chado cvs to match our expectations? (yes/no) [no]` and similar changes later?
> 
> * Another justification for this is if I want to redirect output to a file, I can safely respond to all invisible prompts by hitting enter several times.

You're right 🙈 I changed the defaults as you suggested!

Another note though, you should run `drush trp-check-terms --help`. There are options that take into account you may run this command over and over again as you fix things. The case you are mentioning likely would benefit from running `drush trp-check-terms --auto-expand --no-fix --chado_schema=chado_prod`. Then it won't prompt you at all ;-p

2024-06-18 16:59 UTC, dsenalik commented
Example output of duplicate YAML detection which will happen until PR #1901 is merged
```
YAML Issues: Duplicated term definitions in the site YAML.
----------------------------------------------------------

We have detected 2 duplicated term definition(s) present in your YAML file. You will want to contact the developers to let them know the following output:
 * Term array design (EFO:0000269) was defined more than once.
 * Term lineage (local:lineage) was defined more than once.
```

2024-06-19 00:53 UTC, dsenalik commented
🙃 Tripal 3 defined two terms in the `tripal_contact` vocabulary in `tripal_chado/files/tcontact.obo`:
```
[Term]
id: TCONTACT:0000004
name: Organization
is_a: TCONTACT:0000001 ! Contact Type

[Term]
id: TCONTACT:0000018
name: Organization
def: A generic term for any organization.
relationship: part_of TCONTACT:0000015 ! Affiliation
```

In the Tripal 3 docker, when the OBO was imported, the second one became `Organization(TCONTACT:0000018)`
In my case, for whatever reason, the first one became `Organization (TCONTACT:0000004)`

Likewise with the "Department" term, it is also in there twice.

Anyway, when I import my Chado into Tripal 4, and try to prepare Chado, I am seeing
...
```
 [notice] Step 4: Loading terms...
 [notice] Percent complete: 0%. Memory: 38,689,072 bytes.
 [notice] Percent complete: 0%. Memory: 38,689,072 bytes.
 [notice] Percent complete: 3.57 %. Memory: 38,689,104 bytes.
 [notice] Percent complete: 7.14 %. Memory: 38,689,136 bytes.
 [notice] Percent complete: 10.71 %. Memory: 38,689,168 bytes.
 [error]  ERROR: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "cvterm_c1"
DETAIL:  Key (name, cv_id, is_obsolete)=(Organization, 9, 0) already exists.:
  UPDATE "chado"."cvterm" SET "name"=:db_update_placeholder_0, "definition"=:db_update_placeholder_1, "is_obsolete"=:db_update_placeholder_2, "is_relationshiptype"=:db_update_placeholder_3
WHERE "cvterm_id" = :db_condition_placeholder_0; Array
(
)
```
9 is the tripal_contact cv_id

So tomorrow's project may be to figure out why this is happening...

2024-06-19 15:22 UTC, dsenalik commented
Something that should be added, check for our standard entity record identifier term. If it was not present in the Tripal 3 site you may get this error
`Exception: Cannot create a StorageProperty object for entity type "tripal_entity" field type "chado_string_type_default", key "record_id" as accession for the property term is not recognized: "SIO:000729" in Drupal\tripal\TripalStorage\StoragePropertyBase->__construct() (line 77 of modules/contrib/tripal/tripal/src/TripalStorage/StoragePropertyBase.php). `

I see this if I get everything ready for Chado prepare, and at that point make a database backup. If I restore from this backup, I see the error.

2024-06-29 17:08 UTC, dsenalik commented
Additional test procedure to reproduce the situation causing the error I saw, and see if this is properly flagged after commit TBD. We will need a new docker so that these terms get checked, because this commit modified some YAML.
```
UPDATE cvterm SET name='Organization (TCONTACT:0000004)' WHERE name='Organization' AND cv_id=(SELECT cv_id FROM cv WHERE name='tripal_contact');
UPDATE 1
UPDATE cvterm SET name='Organization' WHERE name='Affiliated Organization' AND cv_id=(SELECT cv_id FROM cv WHERE name='tripal_contact');
UPDATE 1
UPDATE cvterm SET name='Department (TCONTACT:0000009)' WHERE name='Department' AND cv_id=(SELECT cv_id FROM cv WHERE name='tripal_contact');
UPDATE 1
UPDATE cvterm SET name='Department' WHERE name='Affiliated Department' AND cv_id=(SELECT cv_id FROM cv WHERE name='tripal_contact');
UPDATE 1
SELECT T.name, X.accession from cvterm T left join dbxref X on T.dbxref_id=X.dbxref_id where cv_id=(SELECT cv_id FROM cv WHERE name='tripal_contact') order by cvterm_id;
              name               | accession 
---------------------------------+-----------
 Organization (TCONTACT:0000004) | 0000004
 Department (TCONTACT:0000009)   | 0000009
 Department                      | 0000016
 Organization                    | 0000018
```
So that reproduces the situation that I had. Running the validation:
```
...
  Organization (TCONTACT:0000004)                                           26   27    205     **202**     
  Department (TCONTACT:0000009)                                             26   27    204     **203**     
...
 Would you like more details regarding the errors we found? (yes/no) [yes]:
 > 

Term (cvterm/dbxref) Issues.
----------------------------

We have detected 2 Term(s) with a key deviation from what is expected. Specifically:
+---------------------------------+-------------------------------------------+------------------+------------------+------------------+
| TERM                            | MESSAGE                                   | COLUMN           | EXPECTED         | YOURS            |
+---------------------------------+-------------------------------------------+------------------+------------------+------------------+
| Organization (TCONTACT:0000004) | Broken Connection between cvterm + dbxref | cvterm.dbxref_id | TCONTACT:0000004 | TCONTACT:0000018 |
| Department (TCONTACT:0000009)   | Broken Connection between cvterm + dbxref | cvterm.dbxref_id | TCONTACT:0000009 | TCONTACT:0000016 |
+---------------------------------+-------------------------------------------+------------------+------------------+------------------+
```
This does flag the situation that will violate the unique constraint when Chado is prepared, though maybe not in a super-obvious way...

2024-06-29 17:21 UTC, dsenalik requested changes
Everything is now working for me, I would approve except one change requested 😁. Need to validate that the chado schema exists in a nice way. To reproduce, misspell your chado schema name:
![2024-06-29_splunge](https://github.com/tripal/tripal/assets/8419404/5dc46b86-524e-470b-84ce-99f7d9da6a29)

2024-07-10 14:45 UTC, Ferrisx4 commented
I've been testing this both in the Docker (works as intended), as well as on an imported Chado schema from the i5k database. I'm running into a few issues:
```shell
[ERROR] We missed a case with the dbxref for reference annotation (SBO:0000552). These are the dbxrefs we have to work 
         with: Array                                                                                                    
         (                                                                                                              
             [1006] => stdClass Object                                                                                  
                 (                                                                                                      
                     [dbxref_id] => 1006                                                                                
                     [accession] => 0000552                                                                             
                     [db_name] => SO                                                                                    
                 )                                                                                                      
                                                                                                                        
         ) 
```

This is then followed by 
```shell
Error: Object of class stdClass could not be converted to string in /var/www/t4/web/modules/contrib/tripal/tripal_chado/src/Commands/ChadoCheckTermsAgainstYaml.php on line 637
```

The object in question is indeed not a string, but an array:
```php
stdClass Object
(
    [dbxref_id] => 113276
    [accession] => 0000004
    [db_name] => TContact
)
```

I'm still a little fuzzy on all of this term checking, and all of the different `// CASE:`s that are checked, but have you seen any issues like this? I think 
>chado vocabularies and cvterms often become a bit eccentric over the years ;-p

is a bit of an understatement.

2024-07-10 20:48 UTC, Ferrisx4 commented
My second error above was just caused by a missing reference to the actual dbxref_id value. Under the standard T4 Docker, this section of code doesn't get called, so it probably slipped under the radar, but i5k's DB triggered it.

For the case that is missed, indicated by the first error, I can provide values from the database that may help cover this, but I'm not sure what would be pertinent.

Also, now that the second error above isn't causing the check function to crash entirely, I run into an error on line 651 where $term_info['db_name'] doesn't exist (another case of the code never being run on a more ideal database state). Working on a fix for this now...

2024-07-12 14:08 UTC, Ferrisx4 commented
@laceysanderson In the `chadoCheckTerms_reportProblem_eccentricCVTerm()` function, do we want to default to non destructive like the other fixes? This argument is missing when calling `$this->askOrRespectOptions()`

2024-07-12 15:01 UTC, dsenalik commented
> @laceysanderson In the `chadoCheckTerms_reportProblem_eccentricCVTerm()` function, do we want to default to non-destructive like the other fixes? This argument is missing when calling `$this->askOrRespectOptions()`

I definitely vote non-destructive ( !💣 )

2024-07-12 20:21 UTC, dsenalik commented
I can trigger the code at line 651 to be executed with
`update chado.dbxref set db_id=2 where dbxref_id=(select dbxref_id from chado.cvterm where name='accession');`
(This is the very first term checked.)
and it generates
```
 [warning] Undefined array key "db_name" ChadoCheckTermsAgainstYaml.php:651
```
...
```
The following table summarizes the terms.
 ------------------------------------------------------------------------- ------ ------ -------- -------- 
  YAML Term                                                                 CV     DB     CVTERM   DBXREF  
 ------------------------------------------------------------------------- ------ ------ -------- -------- 
  accession (CO_010:0000044)                                                12      20    2811      3117   <-- 3117 is red
```
...
```
Term (cvterm/dbxref) Issues.
----------------------------

We have detected 1 Term(s) with a key deviation from what is expected. Specifically:
+----------------------------+-----------------------------------------------+--------------+----------+-------+
| TERM                       | MESSAGE                                       | COLUMN       | EXPECTED | YOURS |
+----------------------------+-----------------------------------------------+--------------+----------+-------+
| accession (CO_010:0000044) | Wrong db but dbxref connected to right cvterm | dbxref.db_id |          | OBI   |
+----------------------------+-----------------------------------------------+--------------+----------+-------+
```
I'm going to push a commit to fix this, then the output will be
```
We have detected 1 Term(s) with a key deviation from what is expected. Specifically:
+----------------------------+-----------------------------------------------+--------------+----------+-------+
| TERM                       | MESSAGE                                       | COLUMN       | EXPECTED | YOURS |
+----------------------------+-----------------------------------------------+--------------+----------+-------+
| accession (CO_010:0000044) | Wrong db but dbxref connected to right cvterm | dbxref.db_id | CO_010   | OBI   |
+----------------------------+-----------------------------------------------+--------------+----------+-------+
```

2024-07-13 14:25 UTC, dsenalik commented
Well Lacey is busy telling people about Tripal, so I went ahead and fixed the ugly stuff that happens when the chado schema does not exist. With commit https://github.com/tripal/tripal/pull/1895/commits/9697044e622289d2a7a98e4094e5ef45d21a2719 you will now see this instead
![2024-07-13_invalid-schema](https://github.com/user-attachments/assets/25cf994d-487b-424e-ac8f-55f8a93bf5dd)

But I didn't like still seeing the red X, so with commit https://github.com/tripal/tripal/pull/1895/commits/ddad6f5ec88f83eb2d9f43acb7c525f1164c80b7 I went ahead and split the main function into two parts to reduce the cognitive complexity (it was a pretty long function 🙃) since it did two separate things, 1. find, then 2. report

2024-07-13 15:05 UTC, dsenalik approved these changes

2024-07-15 16:16 UTC, dsenalik commented
Sean's error:
![2024-07-15_tbd](https://github.com/user-attachments/assets/252f820d-ef1a-43b1-83df-d1f80b400dbc)

2024-07-22 16:21 UTC, laceysanderson commented
Thanks for all the fixes @dsenalik and @Ferrisx4, these look great :-)

2024-07-22 16:23 UTC, merged

2024-07-23 20:09 UTC, Ferrisx4 commented
I know this is closed but for convenience and organization sake, I'll put this here:

I just realized the issue I'm having as described in [my last comment on the tripal doc issue #82](https://github.com/tripal/tripal_doc/issues/82#issuecomment-2239484897) was already brought up by @dsenalik up above: https://github.com/tripal/tripal/pull/1895#issuecomment-2177319905.

In that comment, the workaround is a simple renaming. I'd like to also point out that, at least in the database I'm using, there are two "TContact"-like entries in the db table:

```sql
select * from chado.db where name ilike '%contact%';
 db_id |   name   |                                                description                                                |           urlprefix            |        url         
-------+----------+-----------------------------------------------------------------------------------------------------------+--------------------------------+--------------------
   116 | TContact |                                                                                                           |                                | 
   400 | TCONTACT | Tripal Contact Ontology. A temporary ontology until a more formal appropriate ontology can be identified. | cv/lookup/TCONTACT/{accession} | cv/lookup/TCONTACT
```

In our db, we have a number of dbxrefs that point to the `TContact` one, with the empty rows, and none that point to the proper one (`TCONTACT`).

Interestingly, the Chado term checker flags two rows as having the dbxref in red:
```
The following table summarizes the terms.
 ------------------------------------------------------------------------- ----- ----- -------- ---------- 
  YAML Term                                                                 CV    DB    CVTERM   DBXREF    
 ------------------------------------------------------------------------- ----- ----- -------- ---------- 
  Organization (TCONTACT:0000004)                                           24    400   39488     113276   
  Department (TCONTACT:0000009)                                             24    400   39493     113281   
```
and the summary:
```
Term (cvterm/dbxref) Issues.
----------------------------

We have detected 2 Term(s) with a key deviation from what is expected. Specifically:
+---------------------------------+-----------------------------------------------+--------------+----------+---------+
| TERM                            | MESSAGE                                       | COLUMN       | EXPECTED | YOURS   |
+---------------------------------+-----------------------------------------------+--------------+----------+---------+
| Organization (TCONTACT:0000004) | Wrong db but dbxref connected to right cvterm | dbxref.db_id | TCONTACT | OBO_REL |
| Department (TCONTACT:0000009)   | Wrong db but dbxref connected to right cvterm | dbxref.db_id | TCONTACT | OBO_REL |
+---------------------------------+-----------------------------------------------+--------------+----------+---------+
```
In the database, the two dbxrefs that were flagged in red, 113276 and 113281, both point to db_id 116, the erroneous TContact from earlier. Changing this value from 116 to 400 satisfies the Chado term check. 

Since the functionality was mostly there, and this was subsequently merged, I can open a new issue if we think this case needs to be handled differently, at least with different language, as it wasn't immediately clear what the solution was, or if the solution doesn't necessarily work with Doug's suggestion above, which I will test.

2024-07-24 21:02 UTC, dsenalik commented
One thing I would like to see added is a case-insensitive check for more that one DB or CV having the same name but different case. I think I had something like that a few years back that I cleaned up, it would just be a nice warning that would be simple to add I think.

That OBO_REL is odd, it would be good to know how to reproduce it because it seems suspicious, there could be a bug in there.