Tv4g1 issue1637 organism image
tripal/tripal pull request #1915
Opened 2024-06-20 22:43 UTC by spficklin

# Tripal 4 Core Dev Task

### Issue #1637

### Tripal Version:  4.x

## Description

Adds an orgnanism image field to the organism content type.  This PR adds the field which uses the Drupal image field and also adds it to the default layout of the organism.  

## Testing?

- On a new tripal site:
   1.  Create an oraganism and add as many images as you like.  Upon saving, you should see  the images on the page.  
   2.  Go to `Tripal` > `Page Structure` and click on "manage display" under the "organism' content type.  Click the 'Apply Tripal Layout' button.   Now, return to the organism page and the images should be in a new details box named "Images"
- On an existing tripal site
   1.  Pull the code from this branch
   2. Go to `Tripal` > `Configuration` and click on 'Tripal Field Collection'. 
   3. Delete the collection named "Default Chado Fields"
   4. Clear the cache
   5. Re-import the field collection by going to `Tripal` > `Page Structure`  and click "Import Type Collection".  Check the box labeled "General Content Types (Chado)".  Run the job. You should now have an organism image field.  
   6. Create or edit an oraganism and add as many images as you like.  Upon saving, you should see  the images on the page.  
   2.  Go to `Tripal` > `Page Structure` and click on "manage display" under the "organism' content type.  Click the 'Apply Tripal

2024-06-20 23:30 UTC, spficklin commented
Well dang. It's not passing tests.  Fixing now...

2024-06-23 13:09 UTC, dsenalik commented on tripal_chado/config/install/tripal.tripalfield_collection.general_chado.yml
> +            termAccession: "0000101"
Just a comment, I have been thinking for a while about creating a field for the `chado.eimage` table. On CarrotOmics I have a Tripal 3 field to do this and use this very term for the field. Would it be a conflict to use the same term as this field uses?

2024-06-23 13:22 UTC, dsenalik requested changes
I tested as described. I could add and remove images as expected.
A note, by accident I added the same file twice and this was allowed. I think this is fine though, and it's probably a Drupal thing anyway.

I did note something else. On a new site after applying layout, the organism appears as
![2024-06-23_newsite](https://github.com/tripal/tripal/assets/8419404/180ebaa3-e2a5-4181-bc2f-7ab794a2515b)

When I did the existing site test, I also tried applying the layout, and in this case the organism field is not inside a group.
![2024-06-23_oldsite](https://github.com/tripal/tripal/assets/8419404/dcfcdc88-14c6-4f1d-b04d-a61aa04f0d25)
I suspect the tripal layout YAML needs to be reloaded, so I wonder if this PR needs an update hook?

And tests are not passing 😆

2024-06-23 22:46 UTC, spficklin commented
Oh, good point about needing an update hook.   In the testing instructions I gave I walk you through reloading the YAML but we can't expect a user to do that on an existing site. I'll add an update hook.

Regarding the term used for this field.  I think we need to talk more on it.  We will probably want to use this term for any image for any content type.  I'm not sure if that's a problem or not. It is an image.  Does the term need to be more specific (e.g. organism image).  I think we need some conversation about that.

2024-10-10 23:20 UTC, laceysanderson commented
This PR is causing schema issues and brought to light the issue described in #1999. Since this PR (1) has very little code, (2) has been open for 1/2 a year and (3) is now dependant on the linked issue which is not easy to fix, I think it should just be closed at this point. We can revisit adding an organism field to these collections at a later point if there is enough demand.

2024-10-10 23:20 UTC, closed without merging