Tv4g2 issue2036 tripaldbx extension not installed
tripal/tripal pull request #2037
Opened 2024-11-22 19:59 UTC by Ferrisx4

# Bug Fix

### Issue # 2036

## Description

This change removes all traces of `tripaldbx.settings` by moving the respective config lines into Tripal itself.

This change is necessary because it prevents sites from being able to import full site configurations that had been generated from sites that still had `tripaldbx.settings` records. 

## Testing?

1. Build a completely new Docker with this branch†
2. Export a full site configuration using the Configuration Manager: `/admin/config/development/configuration/full/export`
3. Make a simple change in the site's configuration, such as rearranging the fields on the Organism content type: `/admin/structure/bio_data/manage/organism/display`
5. Re-import the config archive: `/admin/config/development/configuration/full/import`
6. Do **not** get the following error message, (or any error message 🤞): `Configuration tripaldbx.settings depends on the tripaldbx extension that will not be installed after import.`, and apply the changes.
7. Navigate back to `/admin/structure/bio_data/manage/organism/display` to see that your changes made after the export (step 2) were reverted.
    

† @dsenalik had an issue where Docker kept files around that had been deleted during the build process. His workaround was to [use empty placeholder files](https://github.com/tripal/tripal/issues/2036#issuecomment-2494607062). If your Docker builds and the two deleted files remain, you'll also have to use placeholders.

2024-11-23 14:29 UTC, dsenalik requested changes
1. We need to change remaining `tripaldbx.settings` in the tests, this command will do it: `sed -i -e 's/tripaldbx.settings/tripal.settings/' tripal/tests/src/Unit/TripalDbx/TripalDbxUnitTest.php tripal/tests/src/Kernel/TripalDBX/ConnectionTest.php tripal/tests/src/Kernel/TripalDBX/SchemaTest.php tripal/tests/src/Kernel/TripalDBX/TripalDbxFunctionalTest.php tripal_chado/tests/src/Traits/ChadoTestTrait.php tripal_chado/tests/src/Kernel/ChadoTestKernelBase.php`
2. I think we should have the two placeholder files in this PR - they can be removed later after nightly docker builds - that way nobody needs to do anything special. I have another obsolete file from publish that should be remove, I can make a PR to do it later.
3. Sadly, I think we need an update hook for existing sites

Running tests locally with items 1 and 2 changed
```
PHPUnit 10.5.38 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.13
Configuration: /var/www/drupal/web/modules/contrib/tripal/phpunit.xml

...............................................................  63 / 262 ( 24%)
....III..................I...............IIII................I. 126 / 262 ( 48%)
..............................................................F 189 / 262 ( 72%)
............................................................... 252 / 262 ( 96%)
...I......                                                      262 / 262 (100%)

Time: 01:26:59.986, Memory: 135.45 MB
```
This failing test is unrelated, will be fixed by PR #2039 😆

2024-11-25 17:06 UTC, dsenalik commented on tripal/config/install/tripal.settings.yml
> +# without delimitation characters (ie. starting and indening '/').
```suggestion
# without delimitation characters (ie. starting and ending '/').
```

2024-11-25 20:25 UTC, dsenalik commented
I think the update hook is going to be necessary.
I build a docker on 4.x, then switched to this branch. Import failed, even after cache rebuild
![8036 4 x](https://github.com/user-attachments/assets/7810b209-8c5d-4aeb-9769-2a13d8b8eb64)

2024-11-27 16:04 UTC, Ferrisx4 commented
Thanks @dsenalik for the sed command :) Changes have been applied in https://github.com/tripal/tripal/pull/2037/commits/d6d3c085b26372451165079d18bcd3a71655f64a.

I'll work on an update hook to hopefully close out this issue.

2024-12-16 03:31 UTC, dsenalik commented on tripal/tripal.install
> + */
```suggestion
/**
 * Removes tripaldbx.settings, these have been moved to tripal.settings
 */
```

2024-12-16 03:44 UTC, dsenalik requested changes
I built a docker on 4.x
Switched to this branch
Ran the update hook
Exported configuration
Switched order of genus and species on organism
Imported configuration
No errors, and the order was correctly reverted to the original

Only one change needed, the header for the update hook wasn't finished. With suggested change you will see
```
root@2732b8cc8989:/var/www/drupal# drush updatedb
 -------- ----------- --------------- ------------------------------------- 
  Module   Update ID   Type            Description                          
 -------- ----------- --------------- ------------------------------------- 
  tripal   10402       hook_update_n   10402 - Removes tripaldbx.settings,  
                                       these have been moved to             
                                       tripal.settings                      
 -------- ----------- --------------- ------------------------------------- 


 ┌ Do you wish to run the specified pending updates? ───────────┐
 │ ● Yes / ○ No                                                 │
 └──────────────────────────────────────────────────────────────┘
```

2024-12-16 14:39 UTC, Ferrisx4 commented on tripal/tripal.install
> + */
Good catch! I'm fine with that change.

2024-12-16 17:09 UTC, dsenalik approved these changes
Looks good!

2024-12-16 18:38 UTC, merged