Add support for postgresql 17
tripal/tripal pull request #2055
Opened 2024-12-09 16:16 UTC by dsenalik

# New Feature

### Closes #2048

## Description
This advances the highest version of Postgresql used for testing and dockerfiles from 16 to 17

## Testing?
1. See if tests pass (probably not right away as there is no Drupal dockerfile for 17 yet)
2. See if you can build a docker

2024-12-10 00:26 UTC, dsenalik commented
A simple patch file is not possible, as there are multiple places where errors will occur.
I made changes to the chado 1.3 sql files themselves 😟.
Some changes are from this patch file:
https://github.com/GMOD/Chado/blob/1.4/chado/migrations/V1.3.3.007__fix_search_path.sql
which references this issue:
https://github.com/GMOD/Chado/issues/65
which explains what is going on.

The later changes are just to add public to the search path when accessing box functions

With these changes I can finally build a Postgresql 17 docker locally
![pg17](https://github.com/user-attachments/assets/9454fa2d-e0ee-47d6-b965-0272296f66bb)

2024-12-17 22:35 UTC, laceysanderson reviewed
Code-wise everything is looking good so far. I haven't looked through the chado schema changes yet though.

2024-12-17 22:35 UTC, laceysanderson commented on .github/workflows/SCHEDULE-buildDrupalDocker.yml
> +        if: ${{ matrix.drupal-version == '10.3.x-dev' && matrix.php-version == '8.3' && matrix.pgsql-version == '17' }}
Bump the Drupal version for latest in the schedules docker drupal base image as well.
```suggestion
        name: Build latest using 11.1.x-dev, PHP 8.3, PgSQL 17
        if: ${{ matrix.drupal-version == '11.1.x-dev' && matrix.php-version == '8.3' && matrix.pgsql-version == '17' }}
```

2024-12-20 19:29 UTC, laceysanderson requested changes
So while reviewing the chado schema changes in this PR an issue popped up:

- there are changes to the parts files that are not represented in the original default_schema file. This makes it possible that we will lose these changes in the future if the parts ever need to be regenerated.
- unfortunatly the parts-specific changes are search_path focused which means we can't move these into the original default_schema file as they will be altered by the chunking script.

There are two possible solutions for this:
1. Update the chunking script to be a lot smarter about search_path. This is harder then it sounds because when the parts are applied there are additional changes to search path added.
2. Divide the original default_schema into sections first by moving the functions, views and other schema into different files. Then we only chunk and alter the schema name for the chado portion. This allows us to control the search_path better and more holistically for the functions and views.

I'm taking a stab at the second solution right now.

2024-12-21 20:37 UTC, laceysanderson approved these changes
Based on time constraints, I've put the more ideal solution on hold and documented it in #2072.

The fix in this PR is effective but also means we can no longer regenerate the parts. As such, I removed the original single `default_schema-1.3.sql` file that those parts were generated from to prevent us from accidentally losing these changes.

I've also tested this and looked through it in detail and feel confident in the current solution :-) Thanks for the work @dsenalik! I believe this is ready to merge and as such, I've updated the required checks to include PostgreSQL 17 instead of PostgreSQL 16.

2024-12-21 20:50 UTC, merged