Support for Views Tripal Entity Relationship
tripal/tripal pull request #470
Opened 2018-06-22 00:55 UTC by spficklin

Issue #467 

## Type(s) of Change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API-specific change (fix or addition to an API function)
- [ ] Updates documentation (inline or markdown files)

## Description

Currently, it's not possible to create relationships between a Tripal entity and other Drupal related tables such as Taxonomy.  So, for example, if you add the "Taxonomy Term Reference" field to any of your entities you will be able to tag them,  but you can never filter your entities by those tags.  This is because our code for entities doesn't support it in the TripalFieldQuery nor in Views.   This PR fixes both.  It also fixes some major problems with integrating results should we ever have other storage backends... which in fact is the Taxonomy example is one. 

I'm marking this as a release blocker because it fixes some major issues with queries.

## Testing?

To test do the following:
1)  After pulling this branch you will need to fully clear your cache.
2)  Go the Admin > Structure > Taxonomy and create a new vocabulary named "Publication Tags".
3)  Add some new terms to it.  You can pick anything that makes sense to you to tag publications (e.g. "Software", "Genome", etc.).
4)  Go to your publication content type:  Admin > Structure > Tripal Content Types.  Click the 'manage fields' for the Publication type.  Add a new field of type 'Term Reference'.  Name it 'field_pub_tags'. If you give it that exact name then the view I attach to this PR should work.  The following two screen shots show the settings I think are best for testing but it really shouldn't matter what you choose. ![tag_field_settings](https://user-images.githubusercontent.com/1719352/41752230-fc30470c-757a-11e8-93f9-e91da9ab264e.png) ![tag_field_settings2](https://user-images.githubusercontent.com/1719352/41752233-fe8b1b9e-757a-11e8-8c7c-910fdb446202.png)
Note: if you enable the term_reference module you get the nice tree view of terms.
5) Click on the 'Manage Display' field to move your new tags field out of the Disabled section and somewhere that you can see it on the page and save.
6) Now search for a publication entity on your site and add a new tag to by editing the publication and setting the tag.
7) Next create a new view that uses the Publication content type.  For a shortcut you can use the exported view here: [pub_tags-view.txt](https://github.com/tripal/tripal/files/2125795/pub_tags-view.txt).  Here's a screenshot of the settings for the view:  ![pub_tags-view](https://user-images.githubusercontent.com/1719352/41752390-18ff03c2-757c-11e8-9437-54b8049a192f.png)
8)  Now use the view to search for the publication you tagged in step 6.  This view lets you test filters on both Tripal fields (e.g. publcation year) and Taxonomy tags (Drupal field).  You should be able successfully use any combination of both to filter your pubs.

## Additional Notes (if any):

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2018-06-28 13:04 UTC, bradfordcondon commented
For those who follow instructions too literally: Name your field `pub_tag`, **not** `field_pub_tags` (@spficklin you may want to edit instructions) to use the view that stephen has very kindly provided.  (the resulting machine name will be field_pub_tags... i ended up with a field named `field_field_pub_tags` and had to destroy it/start over).

2018-06-28 13:05 UTC, bradfordcondon commented on tripal/includes/TripalFieldQuery.inc
> +      if (array_key_exists($entity_id, $current_results['TripalEntity'])) {
if i do a search that returns no results (IE pick a pub year that is wrong) I get the following errors at this line:


```
Notice: Undefined index: TripalEntity in TripalFieldQuery->_intersectResults() (line 148 of /Users/chet/UTK/tripal/sites/all/modules/tripal/tripal/includes/TripalFieldQuery.inc).
Warning: array_key_exists() expects parameter 2 to be array, null given in TripalFieldQuery->_intersectResults() (line 148 of /Users/chet/UTK/tripal/sites/all/modules/tripal/tripal/includes/TripalFieldQuery.inc).
Notice: Undefined index: TripalEntity in TripalFieldQuery->_intersectResults() (line 148 of /Users/chet/UTK/tripal/sites/all/modules/tripal/tripal/includes/TripalFieldQuery.inc).
Warning: array_key_exists() expects parameter 2 to be array, null given in TripalFieldQuery->_intersectResults() (line 148 of /Users/chet/UTK/tripal/sites/all/modules/tripal/tripal/includes/TripalFieldQuery.inc).
```

2018-06-28 13:06 UTC, bradfordcondon requested changes
Functionality confirmed!  Filtering by tags works.  It also works in combination with filtering by tripal field.

Here's the view succeeding:

![screen shot 2018-06-28 at 9 06 45 am](https://user-images.githubusercontent.com/7063154/42036138-9dacad78-7ab2-11e8-93e7-9434f6fc6ca3.png)

But what happens if we return no results?

<img width="648" alt="screen shot 2018-06-28 at 9 06 17 am" src="https://user-images.githubusercontent.com/7063154/42036119-90838496-7ab2-11e8-9286-cfe508229d66.png">

We should probably fix the error for null results on line 148.

2018-06-28 13:08 UTC, bradfordcondon commented
Note: it gracefully handles the TAG not existing.

![screen shot 2018-06-28 at 9 07 28 am](https://user-images.githubusercontent.com/7063154/42036184-b93d7d74-7ab2-11e8-833e-65bdcd1bc62c.png)

searching for a tag that has no records gives no error (but also no notice... i dont know if thats this PR's job)
![screen shot 2018-06-28 at 9 08 12 am](https://user-images.githubusercontent.com/7063154/42036213-ced8b6e4-7ab2-11e8-9e4a-6fd28e7f7108.png)

2018-06-28 13:34 UTC, bradfordcondon commented
PR made to fix the issues I brought up above.  https://github.com/tripal/tripal/pull/488
Apologies if you'd prefer I commit directly...

2018-06-29 18:10 UTC, spficklin commented
@bradfordcondon I've merged your PR into this one.  Are you satisfied now that this is merged in? Perhaps @shawnawsu can provide a second review now.

2018-06-29 18:21 UTC, bradfordcondon approved these changes
thanks!

2018-06-29 18:53 UTC, shawnawsu commented
Just finished test PR #453, will now test this one.

2018-06-29 20:54 UTC, shawnawsu commented
I test this and it works for me including the updated graceful fail. So I approve this, will add the tag.

2018-06-29 20:56 UTC, merged