Fix relationship widget unset variable errors
tripal/tripal pull request #711
Opened 2018-10-09 18:48 UTC by almasaeed2010

Simple fix to check if a field exists in the form_state array before attempting to access it.

## Testing?

Let me know if the code isn't clear enough.

Thanks!

2018-10-12 17:08 UTC, laceysanderson requested changes
Other then my one comment, looks good

2018-10-12 17:08 UTC, laceysanderson commented on tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship.inc
> +      $object_name = isset($item['object_name']) ? $item['object_name'] : null;
I think it's safer to return `''` if the item is not set. This would also be consistent with the `$type_name` above.

2018-10-15 15:17 UTC, almasaeed2010 commented
Hello @laceysanderson thanks for the review! I submitted a new commit to address your suggestion.

Thanks!

2018-10-15 17:02 UTC, laceysanderson approved these changes

2018-10-16 18:22 UTC, bradfordcondon commented
seems very straight forward to me.  thank you @almasaeed2010

2018-10-16 18:28 UTC, merged